image: node0.10
script:
  - npm install
  - npm test
  - nvm install 0.10.29
  - nvm use 0.10.29
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
publish:
  npm:
    email: {{npm_drone_email}}
    username: {{npmdeployusername}}
    password: {{npmdeploypassword}}
    branch: master
