apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-google-admin-sdk
  description: node.js library for Google's Admin SDK
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
