# taken from https://developers.google.com/oauthplayground/
# TODO: use discovery API: https://developers.google.com/discovery/
module.exports =
  'Adsense Management': 'https://www.googleapis.com/auth/adsense'
  'Google Affiliate Network': 'https://www.googleapis.com/auth/gan'
  'Analytics': 'https://www.googleapis.com/auth/analytics.readonly'
  'Google Books': 'https://www.googleapis.com/auth/books'
  'Blogger': 'https://www.googleapis.com/auth/blogger'
  'Calendar': 'https://www.googleapis.com/auth/calendar'
  'Google Cloud Storage': 'https://www.googleapis.com/auth/devstorage.read_write'
  'Contacts': 'https://www.google.com/m8/feeds/'
  'Content API for Shopping': 'https://www.googleapis.com/auth/structuredcontent'
  'Chrome Web Store': 'https://www.googleapis.com/auth/chromewebstore.readonly'
  'Documents List': 'https://docs.google.com/feeds/'
  'Directory API Groups': 'https://www.googleapis.com/auth/admin.directory.group'
  'Directory API OrgUnits': 'https://www.googleapis.com/auth/admin.directory.orgunit'
  'Directory API Users': 'https://www.googleapis.com/auth/admin.directory.user'
  'Google Drive': 'https://www.googleapis.com/auth/drive'
  'Google Drive Files': 'https://www.googleapis.com/auth/drive.file'
  'Gmail': 'https://mail.google.com/mail/feed/atom'
  'Google':+' https://www.googleapis.com/auth/plus.me'
  'Groups Provisioning': 'https://apps-apis.google.com/a/feeds/groups/'
  'Google Latitude': 'https://www.googleapis.com/auth/latitude.all.best https://www.googleapis.com/auth/latitude.all.city'
  'Moderator': 'https://www.googleapis.com/auth/moderator'
  'Nicknames Provisioning': 'https://apps-apis.google.com/a/feeds/alias/'
  'Orkut': 'https://www.googleapis.com/auth/orkut'
  'Picasa Web': 'https://picasaweb.google.com/data/'
  'Sites': 'https://sites.google.com/feeds/'
  'Spreadsheets': 'https://spreadsheets.google.com/feeds/'
  'Tasks': 'https://www.googleapis.com/auth/tasks'
  'URL Shortener': 'https://www.googleapis.com/auth/urlshortener'
  'Userinfo - Email': 'https://www.googleapis.com/auth/userinfo.email'
  'Userinfo - Profile': 'https://www.googleapis.com/auth/userinfo.profile'
  'User Provisioning': 'https://apps-apis.google.com/a/feeds/user/'
  'Webmaster Tools': 'https://www.google.com/webmasters/tools/feeds/'
  'YouTube': 'https://gdata.youtube.com'

  # Provisioning API scopes
  'Organization Provisioning': 'https://apps-apis.google.com/a/feeds/policies/'
  'Userinfo - Email': 'https://www.googleapis.com/auth/userinfo.email'
  'User Provisioning': 'https://apps-apis.google.com/a/feeds/user/'

  # Admin SDK scopes
  'Admin Group': 'https://www.googleapis.com/auth/admin.directory.group'
  'Admin OrgUnit': 'https://www.googleapis.com/auth/admin.directory.orgunit'
  'Admin User': 'https://www.googleapis.com/auth/admin.directory.user'